env:
  global:
    - CC_TEST_REPORTER_ID=bf323db0e9a4c04daa19494a25ef4a7d90b48dec589798375dd52162b917ae0c
language: node_js
node_js:
  - "node"
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn test --coverage
  - yarn build
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
cache:
  yarn: true
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT